---
title: "Three_Four"
author: "Beau Harrison. Edits: Rodrigo Valdes. Waffles: Rafael Cruz Gil"
date: "April 25, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(waffle)
```

```{r}
# General issues
blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )
```

```{r}
# Function to create  pie
pie_function <- function(df, order, color_baseline, flavor) {
  
  df$flavor <- factor(df$flavor, flavor[order])
  color_array <- color_baseline[order]
  
  bp <- ggplot(df, aes(x="", y=number, fill = flavor)) + 
    geom_bar(width = 1, stat = "identity")

  pie <- bp + coord_polar("y", start=0)

  pie +  
    blank_theme + theme(axis.text.x=element_blank()) + 
    scale_fill_manual(values= color_array)
}
```

# 3. One to one comparisons.

Question: Is the size of the orange slice bigger than the lemon slice?

Intuition: Does the position matter?

```{r}
flavor <- c('vanilla','chocolate','strawberry', 'lemon', 'orange')
number <- c(14, 17, 21, 23, 25)
order_1 = c(1,2,3,4,5)
order_2 = c(1,2,3,5,4)
order_3 = c(4,1,2,3,5)
order_4 = c(1,4,2,3,5)
order_5 = c(1,2,4,3,5)


three_df <- data.frame(flavor, number)
# Factor (the first thing is the input, the order is in the second)

color_baseline = c("lightgoldenrodyellow", "chocolate4", "brown2", "yellow2", "darkorange2")

three1_waffle <- c(`Vanilla` = 14,
                 `Chocolate` = 17,
                 `Strawberry` = 21,
                 `Lemon` = 23,
                 `Orange` = 25)

three2_waffle <- c(`Vanilla` =14,
                 `Chocolate` =17,
                 `Strawberry` = 21,
                 `Orange` = 25,
                 `Lemon` = 23)

three3_waffle <- c(`Lemon` =23,
                 `Vanilla` =14,
                 `Chocolate` =17,
                 `Strawberry` = 21,
                 `Orange` =25)

three4_waffle <- c(`Vanilla` =14,
                 `Lemon` =23,
                 `Chocolate` =17,
                 `Strawberry` = 21,
                 `Orange` =25)

three5_waffle <- c(`Vanilla` =14,
                 `Chocolate` =17,
                 `Lemon` =23,
                 `Strawberry` = 21,
                 `Orange` =25)
```

```{r}
pie_function(three_df, order_1, color_baseline, flavor)

waffle(three1_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("lightgoldenrodyellow", "chocolate4", "brown2", "yellow2", "darkorange2"))

pie_function(three_df, order_2, color_baseline, flavor)

waffle(three2_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("lightgoldenrodyellow", "chocolate4", "brown2", "darkorange2", "yellow2"))

pie_function(three_df, order_3, color_baseline, flavor)

waffle(three3_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("yellow2", "lightgoldenrodyellow", "chocolate4", "brown2", "darkorange2"))

pie_function(three_df, order_4, color_baseline, flavor)

waffle(three4_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("lightgoldenrodyellow", "yellow2", "chocolate4", "brown2", "darkorange2"))

pie_function(three_df, order_5, color_baseline, flavor)

waffle(three5_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("lightgoldenrodyellow", "chocolate4", "yellow2", "brown2", "darkorange2"))

```

# 4. Believes about ordering of slices

Question: Which proportion is bigger? Lemon or orange? Vanilla or chocolate?

Intutition: Do people think that slices are ordered according to sizes?

```{r}
flavor <- c('vanilla','chocolate','strawberry', 'lemon', 'orange')
number <- c(13, 16, 17, 25, 29)

# General Ordering 1
# Baseline
order_1 = c(1,2,3,4,5)
# Change lemon
order_2 = c(1,2,3,5,4)
# Change vanilla
order_3 = c(2,1,3,4,5)

# General Ordering 2 (reverse order)
# Baseline
order_4 = c(5,4,3,2,1)
# Chnage lemon 
order_5 = c(4,5,3,2,1)
# Change vanilla
order_6 = c(5,4,3,1,2)

four_df <- data.frame(flavor, number)
# Factor (the first thing is the input, the order is in the second)

color_baseline = c("lightgoldenrodyellow", "chocolate4", "brown2", "yellow2", "darkorange2")

four1_waffle <- c(`Vanilla` = 13,
                 `Chocolate` = 16,
                 `Strawberry` = 17,
                 `Lemon` = 25,
                 `Orange` = 29)

four2_waffle <- c(`Vanilla` = 13,
                 `Chocolate` = 16,
                 `Strawberry` = 17,
                 `Orange` = 29,
                 `Lemon` = 25)

four3_waffle <- c(`Chocolate` = 16,
                  `Vanilla` = 13,
                 `Strawberry` = 17,
                 `Lemon` = 25,
                 `Orange` = 29)

four4_waffle <- c(`Orange` = 29,
                  `Lemon` = 25,
                  `Strawberry` = 17,
                  `Chocolate` = 16,
                  `Vanilla` = 13)

four5_waffle <- c(`Lemon` = 25,
                  `Orange` = 29,
                  `Strawberry` = 17,
                  `Chocolate` = 16,
                  `Vanilla` = 13)

four6_waffle <- c(`Orange` = 29,
                  `Lemon` = 25,
                  `Strawberry` = 17,
                  `Vanilla` = 13,
                  `Chocolate` = 16)
```

```{r}
# Which slice is bigger? Lemon or orange? 
pie_function(four_df, order_1, color_baseline, flavor)

waffle(four1_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("lightgoldenrodyellow", "chocolate4", "brown2", "yellow2", "darkorange2"))

# Which slice is bigger? Lemon or orange? 
pie_function(four_df, order_2, color_baseline, flavor)

waffle(four2_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("lightgoldenrodyellow", "chocolate4", "brown2", "darkorange2", "yellow2"))

# Which slice is bigger? Vanilla or chocolate?
pie_function(four_df, order_3, color_baseline, flavor)

waffle(four3_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("chocolate4", "lightgoldenrodyellow", "brown2", "yellow2", "darkorange2"))

# Which slice is bigger? Lemon or orange? 
pie_function(four_df, order_4, color_baseline, flavor)

waffle(four4_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("orange2", "yellow2", "brown2", "chocolate4", "lightgoldenrodyellow"))

# Which slice is bigger? Lemon or orange? 
pie_function(four_df, order_5, color_baseline, flavor)

waffle(four5_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("yellow2", "orange2", "brown2", "chocolate4", "lightgoldenrodyellow"))

# Which slice is bigger? Vanilla or chocolate? 
pie_function(four_df, order_6, color_baseline, flavor)

waffle(four6_waffle,
       rows = 10,
       xlab = "One square = One percent",
       colors = c("orange2", "yellow2", "brown2", "lightgoldenrodyellow", "chocolate4"))
```

